import type { PropsWithChildren } from "react";
import { Pressable, Text, TextInput, type TextInputProps, View } from "react-native";
import { AppTheme } from "@/src/theme";

export function Screen({ children }: PropsWithChildren) { return <View style={AppTheme.screen}>{children}</View>; }
export function Card({ title, children }: PropsWithChildren<{ title: string }>) { return <View style={AppTheme.card}><Text style={AppTheme.cardTitle}>{title}</Text>{children}</View>; }
export function Metric({ label, value }: { label: string; value: string }) { return <View style={AppTheme.metric}><Text style={AppTheme.metricLabel}>{label}</Text><Text style={AppTheme.metricValue}>{value}</Text></View>; }
export function Input({ label, multiline, ...props }: TextInputProps & { label: string }) { return <View style={AppTheme.inputGroup}><Text style={AppTheme.label}>{label}</Text><TextInput style={[AppTheme.input, multiline && { minHeight: 96, textAlignVertical: "top" }]} multiline={multiline} placeholderTextColor={AppTheme.colors.muted} {...props} /></View>; }
export function Button({ title, onPress, variant = "primary" }: { title: string; onPress: () => void; variant?: "primary" | "secondary" }) { const secondary = variant === "secondary"; return <Pressable onPress={onPress} style={[AppTheme.button, secondary && AppTheme.buttonSecondary]}><Text style={[AppTheme.buttonText, secondary && AppTheme.buttonTextSecondary]}>{title}</Text></Pressable>; }
export function SegmentedControl({ value, onChange, options }: { value: number; onChange: (value: number) => void; options: number[] }) { return <View style={AppTheme.segmented}>{options.map((option) => <Pressable key={option} onPress={() => onChange(option)} style={[AppTheme.segment, option === value && AppTheme.segmentActive]}><Text style={[AppTheme.segmentText, option === value && AppTheme.segmentTextActive]}>{option}</Text></Pressable>)}</View>; }
export function ChoiceControl<T extends string>({ value, onChange, options }: { value: T; onChange: (value: T) => void; options: Array<{ value: T; label: string }> }) { return <View style={AppTheme.choiceWrap}>{options.map((option) => <Pressable key={option.value} onPress={() => onChange(option.value)} style={[AppTheme.choice, option.value === value && AppTheme.choiceActive]}><Text style={[AppTheme.choiceText, option.value === value && AppTheme.choiceTextActive]}>{option.label}</Text></Pressable>)}</View>; }
export function ListRow({ title, detail, value }: { title: string; detail: string; value?: string }) { return <View style={AppTheme.listRow}><View style={AppTheme.listText}><Text style={AppTheme.listTitle}>{title}</Text><Text style={AppTheme.listDetail}>{detail}</Text></View>{value ? <Text style={AppTheme.listValue}>{value}</Text> : null}</View>; }

